USE ApuestaDB;
GO
SET NOCOUNT ON;
PRINT '== CHECK Auditoria ==';
SELECT name FROM sys.check_constraints WHERE parent_object_id = OBJECT_ID('dbo.Auditoria');
PRINT '== CHECK Notificacion ==';
SELECT name FROM sys.check_constraints WHERE parent_object_id = OBJECT_ID('dbo.Notificacion');
PRINT '== dup tipo+numero ==';
SELECT tipo_documento, numero_documento, COUNT(*) AS n FROM dbo.Usuario GROUP BY tipo_documento, numero_documento HAVING COUNT(*) > 1;
PRINT '== Usuario nulos doc ==';
SELECT COUNT(*) AS nulos FROM dbo.Usuario WHERE numero_documento IS NULL OR numero_documento = '';
PRINT '== Liga ==';
SELECT id, nombre, pais, deporte_id FROM dbo.Liga ORDER BY id;
PRINT '== Temporada ==';
SELECT id, nombre, deporte_id, CONVERT(varchar(10),fecha_inicio,120) AS fi, CONVERT(varchar(10),fecha_fin,120) AS ff FROM dbo.Temporada ORDER BY id;
PRINT '== Calendario ==';
SELECT id, liga_id, equipo_local_id, equipo_visitante_id, estado, CONVERT(varchar(19),fecha_hora,120) AS fh FROM dbo.Calendario ORDER BY id;
PRINT '== Equipo ==';
SELECT id, nombre, liga_id FROM dbo.Equipo ORDER BY id;
PRINT '== Estadio ==';
SELECT id, nombre, ciudad_id FROM dbo.Estadio ORDER BY id;
PRINT '== Pais ==';
SELECT id, nombre, codigo_iso FROM dbo.Pais ORDER BY id;
PRINT '== Ciudad ==';
SELECT id, nombre, pais_id FROM dbo.Ciudad ORDER BY id;
PRINT '== Notificacion ==';
SELECT id, usuario_id, tipo, mensaje FROM dbo.Notificacion ORDER BY id;
PRINT '== HacerApuesta ==';
SELECT id, usuario_id, apuesta_id, tipo_saldo_id, estado, monto FROM dbo.HacerApuesta ORDER BY id;
PRINT '== Recarga ==';
SELECT id, usuario_id, tipo_saldo_id, estado, monto FROM dbo.Recarga ORDER BY id;
PRINT '== LogPago tipo recarga ==';
SELECT id, usuario_id, tipo_saldo_id, monto, saldo_resultante, hacer_apuesta_id FROM dbo.LogPago WHERE tipo = 'recarga' ORDER BY id;
PRINT '== Auditoria LOGIN ==';
SELECT id, usuario_id, tabla_afectada, operacion, detalle FROM dbo.Auditoria WHERE operacion = 'LOGIN' ORDER BY id;
PRINT '== Auditoria total ==';
SELECT id, usuario_id, tabla_afectada, operacion, detalle FROM dbo.Auditoria ORDER BY id;
PRINT '== Servicios ==';
SELECT id, nombre FROM dbo.Servicios ORDER BY id;
PRINT '== Reglas ==';
SELECT id, nombre FROM dbo.Reglas ORDER BY id;
PRINT '== Empresa ==';
SELECT id, nombre FROM dbo.Empresa ORDER BY id;
PRINT '== cols existentes ==';
SELECT COL_LENGTH('dbo.Calendario','estadio_id') AS Cal_estadio, COL_LENGTH('dbo.Equipo','estadio_id') AS Equipo_estadio, COL_LENGTH('dbo.Temporada','liga_id') AS Temp_liga, COL_LENGTH('dbo.Calendario','temporada_id') AS Cal_temporada, COL_LENGTH('dbo.Liga','pais_id') AS Liga_pais, COL_LENGTH('dbo.LogPago','recarga_id') AS LogPago_recarga, COL_LENGTH('dbo.Notificacion','hacer_apuesta_id') AS Notif_ha, COL_LENGTH('dbo.Notificacion','recarga_id') AS Notif_recarga, COL_LENGTH('dbo.Servicios','empresa_id') AS Serv_empresa, COL_LENGTH('dbo.Reglas','empresa_id') AS Reglas_empresa;
PRINT '== UQ Usuario ==';
SELECT i.name FROM sys.indexes i WHERE i.object_id = OBJECT_ID('dbo.Usuario') AND i.is_unique_constraint = 1;
PRINT '== FK existentes a Estadio/Temporada/Pais/Recarga ==';
SELECT fk.name, tp.name AS padre, cp.name AS col FROM sys.foreign_keys fk JOIN sys.tables tp ON tp.object_id = fk.parent_object_id JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id = fk.object_id JOIN sys.columns cp ON cp.object_id = fkc.parent_object_id AND cp.column_id = fkc.parent_column_id WHERE tp.name IN ('Calendario','Equipo','Temporada','Liga','LogPago','Notificacion','Servicios','Reglas') AND fk.name LIKE 'FK_%' ORDER BY tp.name;
GO
